name: Code Style
description: Check code style

runs:
  using: "composite"
  steps:
    - name: Ruff
      shell: bash
      run: |
        uv run ruff format --check
        uv run ruff check

    - name: MyPy
      shell: bash
      run: uv run mypy ./
