name: Deploy
description: Publish package on PyPI
inputs:
  version:
    description: "Package version."
    required: true

runs:
  using: "composite"
  steps:
    - name: Publish
      shell: bash
      run: |
        uvx --from=toml-cli toml set --toml-path=pyproject.toml project.version ${{ inputs.version }}
        uv build
        uv publish
